---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: foo
  namespace: bar
  {{- if .Capabilities.APIVersions.Has "v1/myApi" }}
  annotations:
    capability: ok
  {{- end }}
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app: foo
