---
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion:: policy/v1
{{- else }}
apiVersion:: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: foo
  namespace: bar
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app: foo
